# Generated by Django 4.2.11 on 2024-04-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organiser_of_event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_fees',
        ),
        migrations.AddField(
            model_name='event',
            name='organised_by',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='registration_fee',
            field=models.FloatField(default=0, help_text='Enter Registration Fees For The Event in Rupees'),
        ),
    ]
