# Generated by Django 4.2.11 on 2024-04-10 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_organiser_of_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
