# Generated by Django 4.2.11 on 2024-04-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
