# Generated by Django 4.2.11 on 2024-04-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_of_event',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='organised_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
