# Generated by Django 4.2.11 on 2024-05-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_date_of_event_alter_event_organised_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_of_event',
            field=models.CharField(max_length=100),
        ),
    ]
