# Generated by Django 4.2.11 on 2024-05-23 09:25

import bgfreshnet.freshnet_products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshnet_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freshnetproduct',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_photos/', validators=[bgfreshnet.freshnet_products.models.MaxFileSizeValidator(limit_value=10485760)]),
        ),
    ]
