# Generated by Django 4.2.11 on 2024-05-26 05:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freshnet_products', '0002_alter_freshnetproduct_product_image'),
        ('common', '0002_photolike'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhotoLike',
            new_name='ProductLike',
        ),
    ]
