# Generated by Django 4.2.11 on 2024-04-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_freshnetuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freshnetuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
